routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/getCities/{id}','Auth\RegisterController@getCities');
Route::get('/getBoroughs/{id}','Auth\RegisterController@getBoroughs');


Auth::routes();

// cancelling subscription
Route::post(
    'stripe/webhook',
    '\Laravel\Cashier\Http\Controllers\WebhookController@handleWebhook'
);

Route::group(['middleware' => ['subscriptions','permissions','firsttime']], function () {
   //Route::resource('appointment', 'AppointmentController');
   Route::resource('user/profile', 'UsersController@profile');
   Route::resource('user/invoices', 'UsersController@invoices');
   Route::get('user/invoice/{invoice}', function (Request $request, $invoiceId) {
    return $request->user()->downloadInvoice($invoiceId, [
        'vendor'  => 'Radpido',
        'product' => 'Subscription',
    ]);
   });
   Route::get('users/permission','UsersController@permission');
   Route::get('users/manage','UsersController@manage');
   Route::resource('users', 'UsersController');

   Route::get('home/joinus','HomeController@joinus');
   Route::resource('home', 'HomeController');
   Route::resource('clinic', 'ClinicController');
   Route::resource('dentists', 'DentistsController');

   Route::post('exams/get','PatientExamsController@getExams');
   Route::resource('exams', 'PatientExamsController');

   Route::post('pictogram/getPictogram','PictogramController@getPictogram');
   Route::resource('pictogram', 'PictogramController');

   Route::get('/patient/getCities/{id}','PatientsController@getCities');
   Route::get('/patient/getBoroughs/{id}','PatientsController@getBoroughs');
   Route::post('patients/getPatients','PatientsController@getPatientList');
   Route::get('patients/stats','PatientsController@stats');
   Route::resource('patients', 'PatientsController');

   Route::get('calendar/appointmentdetails/{id}','CalendarController@appointmentdetails');
   Route::put('calendar/updateStatus/{id}','CalendarController@updateStatus');
   Route::get('calendar/appointmentTypes','CalendarController@appointmentTypes');
   Route::post('calendar/addAppointmentType','CalendarController@addAppointmentTypes');
   Route::post('calendar/updateAppointment/{id}','CalendarController@updateAppointment');
   Route::post('calendar/addDocument','CalendarController@addDocument');
   Route::post('calendar/deleteDocument/{id}','CalendarController@deleteDocument');
   Route::post('calendar/getPatientTreatmentDocuments','CalendarController@getPatientTreatmentDocuments');
   Route::post('calendar/addQuotation','CalendarController@addQuotation');
   Route::post('calendar/getQuotation','CalendarController@getQuotation');
   Route::post('calendar/summary','CalendarController@summary');

   Route::post('calendar/getTodaysEvents','CalendarController@getTodaysEvent');
   Route::resource('calendar', 'CalendarController');

   Route::resource('holidays', 'HolidaysController');
   Route::resource('recepnists', 'RecepnistsController');
    Route::resource('consultation', 'ConsultationController');

   // Route::get('treatments/treatmentTypes','TreatmentController@treatmentTypes');
   // Route::post('treatments/addTreatmentType','TreatmentController@addTreatmentTypes');
   Route::post('treatments/getPatientTreatment','TreatmentController@getPatientTreatment');
   Route::resource('treatments', 'TreatmentController');

   Route::get('specialities/get','SpecialityController@get');
   Route::resource('specialities', 'SpecialityController');

   Route::resource('treatmenttypes', 'TreatmentTypesController');

   Route::get('dentalplans/permission','DentalplansController@permission');
   Route::resource('dentalplans', 'DentalplansController');

   Route::get('permissions/addPermissions','PermissionsController@addPermissions');
   //Route::get('permissions/assign','PermissionsController@assign');
   Route::get('permissions/assignPermissions','PermissionsController@assign');
   Route::post('permissions/saveRole','PermissionsController@saveRole');
   Route::resource('permissions', 'PermissionsController');

   Route::get('quoteitems','StockControlController@quoteItems');
   Route::get('getItemHistory/{id}','StockControlController@getItemHistory');
   Route::put('updateStock/{id}','StockControlController@updateStock');
   Route::resource('stockcontrol', 'StockControlController');
   Route::resource('contacts', 'ItemContactsController');

   Route::put('updateReminderUserStatus/{id}','ReminderController@updateReminderUserStatus');
   Route::put('updateStatus/{id}','ReminderController@updateStatus');
   Route::put('unmarkReminder/{id}','ReminderController@unmarkReminder');
   Route::resource('reminders', 'ReminderController');


   Route::resource('agenda', 'AgendaController');
   Route::resource('holidays', 'AppointmentHolidaysController');

   Route::resource('firsttime', 'FirstimeController');

});

Route::get('billing/subscribe', 'UserBilling@subscribeuser');
Route::resource('billing', 'UserBilling');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Ultraware\Roles\Traits\HasRoleAndPermission;
use Ultraware\Roles\Contracts\HasRoleAndPermission as HasRoleAndPermissionContract;
use Laravel\Cashier\Billable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable implements  HasRoleAndPermissionContract
{
    use  HasRoleAndPermission;
    use Notifiable;
    use Billable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','clinic_id','first_time'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The roles that belong to the user.
     */
      // public function roles()
      // {
      //   return $this->hasOne('Ultraware\Roles\Models\Role');
      // }

      public function dentist()
      {
         return $this->belongsTo('App\Dentist','id');
      }


      public function clinic(){
         return $this->belongsTo('App\Clinic','clinic_id','id');
      }

      public function clinicAddress(){
         return $this->hasManyThrough('App\Address','App\Clinic','id','id');
      }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use DB;
use App\User;
use Auth;
use App\Clinic;
use Validator;
use Ultraware\Roles\Models\Permission;
use App\PermissionRole;
use App\Dentist;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $title = "Users";
        $subtitle = 'Informações detalhadas de todos tratamentos';
        $activeClass = "users";
        $user = Auth::user();
        $subtitle = "Informações detalhadas de todos tratamentos";
        // getting users
        $pUsers = array();

        $users = DB::table('users')
            ->leftjoin('role_user', 'users.id', '=', 'role_user.user_id')
            ->where('role_id', '=', '2')
            ->get();

        // getting all roles
        $roleEntry = DB::table('roles')->get();

        foreach ($users as $data) {
            $user = User::find($data->id);
            $clinic = Clinic::find($data->clinic_id);

            // adding data into external array
            $fusers = new \stdClass();
            $fusers->id = $data->id;
            $fusers->name = $data->name;
            $fusers->email = $data->email;
            $fusers->clinic_name = $clinic->name;
            array_push($pUsers, $fusers);
        }
        return view('users.index', compact('title', 'subtitle', 'pUsers', 'activeClass'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = "Add New Dentist Admin";
        $subtitle = "Add New user by Dentist Admin User";
        $activeClass = "users";

        // getting clinics

        $clinics = Clinic::pluck('name', 'id');
        return view('users.create', compact('title', 'subtitle', 'activeClass', 'clinics'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'clinic_id' => 'required',
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6|confirmed',
        ]);

        if ($validator->fails()) {
            return redirect('users/create')
                ->withErrors($validator)
                ->withInput();
        } else {

            // adding dentist
            $clinic = User::create([
                'name' => $request->name,
                'email' => $request->email,
                'clinic_id' => $request->clinic_id,
                'password' => bcrypt($request->password),
            ]);

            // adding dentist Role

            $user = User::find($clinic->id);
            $user->attachRole('2');


            return redirect('users/create')
                ->with('status', 'Dentist Admin Created!');

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        if ($user->trashed()) {
            return response()->json(['status' => 'success', 'message' => "User Deleted!"]);
        } else {
            return response()->json(['status' => 'error', 'message' => 'Some Error Occured!']);
        }
    }

    /**
     * Generate profile as per the current logged in user
     *
     */
    public function profile()
    {
        $user = Auth::user();

        if ($user->hasRole('dentistadmin')) {
            $data = $user;
        }
        if ($user->hasRole('dentist')) {
            $data = Dentist::where('user_id', '=', $user->id)->first();
        }
        if ($user->hasRole('receptionist')) {
            $data = Receptionist::where('user_id', '=', $user->id)->first();
        }

        $title = "User Profile";
        $subtitle = 'Informações detalhadas de todos tratamentos';
        $activeClass = "";
        $subtitle = "Informações detalhadas de todos tratamentos";

        return view('users.profile.index', compact('title', 'subtitle', 'data', 'activeClass'));

    }

    /**
     * Generate profile as per the current logged in user
     *
     */
    public function userDetails()
    {
        $user = Clinic::where('id', '=', Auth::user()->clinic_id)->first();
        return $user;
    }

    /**
     * GENERATE INVOICES
     *
     */

    public function invoices()
    {
        $title = "User Invoices";
        $subtitle = "Download All User Invoices";
        $activeClass = "users";

        $user = User::find(Auth::user()->id);
        $invoices = $user->invoices();
        return view('users.invoices', compact('title', 'subtitle', 'invoices', 'activeClass'));
    }


    /**
     * MANAGE ALL USERS AS PER CLINIC
     *
     */

    public function manage()
    {
        $title = "Manage Clinic User";
        $subtitle = "All the clinic User List";
        $activeClass = "users_management";

        // get all users
        $users = User::where([['clinic_id', '=', Auth::user()->clinic_id], ['role_id', '>', '1']])
            ->leftJoin('role_user', 'users.id', '=', 'role_user.user_id')
            ->leftJoin('roles', 'role_user.role_id', '=', 'roles.id')
            ->select('users.*', 'roles.name AS rolename', 'roles.*', 'users.name AS username')
            ->orderBy('roles.slug', 'ASC')
            ->whereNotIn('users.id', array(Auth::user()->id))
            ->get();

        $i = 0;
        foreach ($users as $data) {
            // if($users[$i]->hasRole('dentist')){
            //    $dentist = Dentist::where('user_id','=',$data->id)->first();
            //    $users[$i]->profile_url =$dentist->profile_url;
            // }
            // if($users[$i]->hasRole('patient')){
            //    $patient = Patient::where('user_id','=',$data->id)->first();
            //    $users[$i]->profile_url =$patient->profile_url;
            // }
            // if($users[$i]->hasRole('receptionist')){
            //    $r = Receptionist::where('user_id','=',$data->id)->first();
            //    $users[$i]->profile_url =$r->profile_url;
            // }
            $i++;
        }

        return view('users.manage', compact('title', 'subtitle', 'users', 'activeClass'));
    }


    /**
     * Adding current controller permissions
     * Manually write all controller methods
     *
     * @route /controller/permission
     */

    public function permission()
    {

        $array = array(
            array('Show All Users', 'userscontroller.index', 'User', 'Show All Users'),
            array('Create New User', 'userscontroller.create', 'User', 'Create New User'),
            array('Manage Users', 'userscontroller.manage', 'User', 'Manage Users'),
        );

        // checking
        foreach ($array as $data) {
            $count = Permission::where('slug', '=', $data[1])->count();
            if ($count == '0') {
                // adding permission
                Permission::create([
                    'name' => $data[0],
                    'slug' => $data[1],
                    'model' => $data[2],
                    'description' => $data[3],
                ]);
            }
        }
        exit;
    }

}

resources/views/users/create.blade.php
@extends('layouts.page')
@section('content')
<div class="main-content">
   <div class="container">

      <!-- TOOLBAR -->
      <div class="toolbar row">
   		<div class="col-sm-6 hidden-xs">
   			<div class="page-header">
   				<h1>{{ $title }} <small>{{ $subtitle }}</small></h1>
   			</div>
   		</div>
   		<div class="col-sm-6 col-xs-12">
   			<div class="toolbar-tools pull-right">
   				<!-- start: TOP NAVIGATION MENU -->
   				<ul class="nav navbar-right">
   					<li>
   						<a href="{{ url('/users')}}" class="new-event MyToolbar">
   							<i class="fa fa-bullseye"></i> View All Users
   						</a>
   					</li>
   				</ul>
   				<!-- end: TOP NAVIGATION MENU -->
   			</div>
   		</div>
   	</div>
      <!-- TOOLBAR -->

      <div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
					<li>
						<a href="#">
							Dashboard
						</a>
					</li>
					<li class="active">
						{{ $title }}
					</li>
				</ol>
			</div>
		</div>

      <div class="panel panel-white" style="margin-top:8px;">
         <div class="panel-heading">
            <h2 class="panel-title"><i class="fa fa-user"></i> {{ $title }}</h2>
         </div>
         <div class="panel-body">
            <form method="POST" action="{{ url('/users') }}" autocomplete="off" enctype="multipart/form-data">

               @if(count($errors))
                  <div class="alert alert-danger">
                     <strong>Whoops!</strong> There were some problems with your input.
                     <br>
                     <ul>
                        @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                     </ul>
                  </div>
               @endif

               <input type="hidden" name="_token" value="{{ csrf_token() }}">

               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
   					<div class="form-group {{ $errors->has('clinic_id') ? 'has-error' : '' }}">
   					   <label for="fname">Select Clinic</label>
                     <div class="clearfix"></div>
                     {!! Form::select('clinic_id', $clinics, 'Select A Clinic',['class' => 'form-control','placeholder' => 'Select a Clinic']) !!}
   					</div>
   				</div>
               <div class="clearfix"></div>
               <div class="col-md-12">
                  <hr>
               </div>

               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
   					<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
   					  <label for="fname">Name</label>
   					  <input class="form-control" id="first_name" name="name" type="text" placeholder="Name" value="{{ old('first_name') }}">
   					</div>
   				</div>
               <div class="clearfix"></div>
               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
   					<div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
   					  <label for="fname">Dentist Admin Email</label>
   					  <input class="form-control" id="email" name="email"  type="text" placeholder="Clinic Email" value="{{ old('email') }}">
   					</div>
   				</div>
               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
   					<div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
   					  <label for="fname">Password</label>
   					  <input class="form-control" id="password" name="password"  type="password" placeholder="Password" value="{{ old('password') }}">
   					</div>
   				</div>
               <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
   					<div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
   					  <label for="fname">Confirm Password</label>
   					  <input class="form-control" id="confirm_password" name="password_confirmation"  type="password" placeholder="Confirm Password" value="{{ old('confirm_password') }}">
   					</div>
   				</div>
               <div class="clearfix"></div>
               <div class="col-md-12">
                  <hr>
               </div>
               <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
   					<div class="form-group">
                     <button class="btn btn-success" type="submit">Create Dentist Admin</button>
   					</div>
   				</div>
            </form>

         </div>
      </div>

   </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.page')
@section('content')
<div class="main-content">
   <div class="container">

      <!-- TOOLBAR -->
      <div class="toolbar row">
   		<div class="col-sm-6 hidden-xs">
   			<div class="page-header">
   				<h1>{{ $title }} <small>{{ $subtitle }}</small></h1>
   			</div>
   		</div>
   		<div class="col-sm-6 col-xs-12">
   			<div class="toolbar-tools pull-right">
   				<!-- start: TOP NAVIGATION MENU -->
   				<ul class="nav navbar-right">
   					<!-- <li>
   						<a href="{{ url('/users/create')}}" class="new-event MyToolbar">
   							<i class="fa fa-user"></i> Add New
   						</a>
   					</li> -->
   				</ul>
   				<!-- end: TOP NAVIGATION MENU -->
   			</div>
   		</div>
   	</div>
      <!-- TOOLBAR -->

      <div class="row">
			<div class="col-md-12">
				<ol class="breadcrumb">
					<li>
						<a href="#">
							Dashboard
						</a>
					</li>
					<li class="active">
						{{ $title }}
					</li>
				</ol>
			</div>
		</div>

      <div class="panel panel-white" style="margin-top:8px;">
         <div class="panel-heading">
   			<h2 class="panel-title"><i class="fa fa-users"></i> Users List</span></h2>
		   </div>
         <div class="panel-body">
            <!-- DISPLAYING USERS -->
            <table class="table datatable table-striped">
         		<thead>
         			<tr>
         				<th class="center">#</th>
         				<th>Name</th>
         				<th>Email</th>
         				<th>Clinic(Associated With)</th>
         				<th>Actions</th>
         			</tr>
               </thead>
               <tbody>
                  <?php
                     if(!empty($pUsers)){
                        foreach($pUsers as $data){
                  ?>
            			<tr>
            				<td class="center">{{ $data->id }}</td>
            				<td>{{ $data->name }}</td>
            				<td>{{ $data->email }}</td>
            				<td>{{ $data->clinic_name }}</td>
            				<td>
                           <div class="btn-group">
                             <button type="button" class="btn btn-warning btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               Action <span class="caret"></span>
                             </button>
                             <ul class="dropdown-menu">
                               <li><a href="#"><i class="fa fa-eye"></i> View User</a></li>
                               <li><a href="#"><i class="fa fa-trash"></i> Delete User</a></li>
                             </ul>
                           </div>
                        </td>
            			</tr>
                  <?php } } ?>
               </tbody>
            </table>
            <!-- DISPLAYING USERS -->

         </div>
      </div>

   </div>
</div>
@endsection

resources/views/users/invoices.blade.php
@extends('layouts.page')
@section('content')
<div class="main-content">
   <div class="container">

      <!-- TOOLBAR -->
      <div class="toolbar row">
   		<div class="col-sm-6 hidden-xs">
   			<div class="page-header">
   				<h1>{{ $title }} <small>{{ $subtitle }}</small></h1>
   			</div>
   		</div>
   		<div class="col-sm-6 col-xs-12">
   			<div class="toolbar-tools pull-right">
   				<!-- start: TOP NAVIGATION MENU -->
   				<ul class="nav navbar-right">
   					<!-- <li>
   						<a href="{{ url('/users/create')}}" class="new-event MyToolbar">
   							<i class="fa fa-user"></i> Add New
   						</a>
   					</li> -->
   				</ul>
   				<!-- end: TOP NAVIGATION MENU -->
   			</div>
   		</div>
   	</div>
      <!-- TOOLBAR -->

      <div class="panel panel-white" style="margin-top:8px;">
         <div class="panel-body">
            <!-- DISPLAYING Invoices -->
               @if(!empty($invoices))
                  <table class="table">
                      @foreach ($invoices as $invoice)
                          <tr>
                              <td>{{ $invoice->date()->toFormattedDateString() }}</td>
                              <td>{{ $invoice->total() }}</td>
                              <td><a href="/user/invoice/{{ $invoice->id }}">Download</a></td>
                          </tr>
                      @endforeach
                  </table>
               @endif
            <!-- DISPLAYING invoices -->

         </div>
      </div>

   </div>
</div>
@endsection

resources/views/users/manage.blade.php
@extends('layouts.page')
@section('content')

    <!-- start: MAIN CONTENT -->
    <div class="main-content">

        <!-- start: CONTAINER -->
        <div class="container">

            <!-- start: MAIN PANEL -->
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 panel" style="background: white;margin-top: 10px">

                <style>
                    .image_cont{width:30px;height:30px;overflow:hidden;}
                    .image_cont img{border-radius:100px;width:100%;height:auto;}
                </style>

                <!-- start: TABLE HEADER -->
                <div class="panel-heading header_t1" style="background: whitesmoke;padding: 0px !important;">

                    <div class="toolbar row" style="min-height: 100px;background: whitesmoke;border: none;opacity:0.8;">

                        <div class="col-sm-6 hidden-xs">

                            <div class="table-header">
                                <h2 style="font-weight: lighter">{{ $title }}</h2>
                                <p style="font-size: large;">Your plan currently has <strong>7</strong> users available</p>
                            </div>

                        </div>

                        <div class="col-sm-6 col-xs-12">

                            <div class="toolbar-tools pull-right" style="padding-top: 10px;">
                                <!-- start: TOP NAVIGATION MENU -->
                                <ul class="nav navbar-right">
                                    <li>
                                        <a href="#" class="print">
                                            <i class="fa fa-users"></i> Change Plan
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="new-event MyToolbar">
                                            <i class="fa fa-link"></i> Send Invite
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="print"  data-id="mainInfo">
                                            <i class="fa fa-print"></i> Imprimir
                                        </a>
                                    </li>
                                </ul>
                                <!-- end: TOP NAVIGATION MENU -->
                            </div>

                        </div>

                    </div>

                </div>
                <!-- end: TABLE HEADER -->

                <!-- start: PANEL BODY -->
                <div class="panel-body" >

                    <!-- start: DISPLAYING USERS -->
                    <table class="table datatable table-striped table-hover table-condensed" id="mainInfo">

                        <!-- start: TABLE HEAD -->
                        <thead>
                        <tr>
                            <th class="hide">#</th>
                            <th class="hidden-print"></th>
                            <th>Nome</th>
                            <th class="center">Tipo Usuário</th>
                            <th>Data Cadastrado</th>
                            <th>Email</th>
                            <th class="hidden-print"></th>
                        </tr>
                        </thead>
                        <!-- end: TABLE HEAD -->

                        <!-- start: TABLE BODY -->
                        <tbody>
                        <?php
                        if(!empty($users)){
                        foreach($users as $data){
                        ?>
                        <tr>
                            <td class="hide">{{ $data->id }}</td>
                            <!-- PROFILE PICTURE -->
                            <td class="hidden-print">
                                <div class="image_cont" style="opacity: 0.8">
                                    @if($data->profile_url != '')
                                        {{ HTML::image(url('/').'/'.$data->profile_url) }}
                                    @else
                                        {{ HTML::image(url('/')."/images/anonymous.jpg") }}
                                    @endif
                                </div>
                            </td>
                            <!-- USERNAME -->
                            <td>{{ $data->username }}</td>
                            <td class="center">
                                @if($data->rolename == 'Admin')
                                    <span class="label label-default" style="background: #1b6d85 !important;opacity: 0.8"> Super Admin </span>
                                @elseif($data->rolename == 'DentistAdmin')
                                    <span class="label label-default" style="background: #75ab00 !important;opacity: 0.8"> Clinic Admin </span>
                                @elseif($data->rolename == 'Receptionist')
                                    <span class="label label-default" style="background: #ad1457 !important;opacity: 0.8"> Receptionist </span>
                                @elseif($data->rolename == 'Dentist')
                                    <span class="label label-default" style="background: #8b1014 !important;opacity: 0.8"> Dentist </span>
                                @endif
                            </td>
                            <td>{{ date('d/m/Y', strtotime($data->created_at)) }}</td>
                            <td style="color: #00a5b3"><strong>{{ $data->email }}</strong></td>
                            <td class="hidden-print">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-white btn-sm btn-squared dropdown-toggle" style="background: white;opacity: 0.9" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Opções &nbsp;<span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-right" style="opacity:0.9;">
                                        <li><a href="{{ URL::route('dentists.show', $data->id) }}"><small><i class="fa fa-user fa-fw"></i>&nbsp; Profile</small></a></li>
                                        <li><a href="#"><small><i class="fa fa-eye fa-fw"></i>&nbsp; Activity</small></a></li>
                                        <li><a href="#"><small><i class="fa fa-info fa-fw"></i>&nbsp; Log</small></a></li>
                                        <li><a href="#"><small><i class="fa fa-check fa-fw"></i>&nbsp; Permissions</small></a></li>
                                        <li><a href="#"><small><i class="fa fa-unlock-alt fa-fw"></i>&nbsp; Make Admin</small></a></li>
                                        <li class="divider"></li>
                                        <li><a href="#"><small><i class="fa fa-ban fa-fw"></i>&nbsp; Remover</small></a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                        <?php } } ?>
                        </tbody>
                        <!-- end: TABLE BODY -->

                    </table>
                    <!-- end: DISPLAYING USERS -->

                </div>
                <!-- end: PANEL BODY -->

            </div>
            <!-- end: MAIN PANEL -->

        </div>
        <!-- end: CONTAINER -->

    </div>
    <!-- end: MAIN CONTENT -->

@endsection