routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/getCities/{id}','Auth\RegisterController@getCities');
Route::get('/getBoroughs/{id}','Auth\RegisterController@getBoroughs');


Auth::routes();

// cancelling subscription
Route::post(
    'stripe/webhook',
    '\Laravel\Cashier\Http\Controllers\WebhookController@handleWebhook'
);

Route::group(['middleware' => ['subscriptions','permissions','firsttime']], function () {
   //Route::resource('appointment', 'AppointmentController');
   Route::resource('user/profile', 'UsersController@profile');
   Route::resource('user/invoices', 'UsersController@invoices');
   Route::get('user/invoice/{invoice}', function (Request $request, $invoiceId) {
    return $request->user()->downloadInvoice($invoiceId, [
        'vendor'  => 'Radpido',
        'product' => 'Subscription',
    ]);
   });
   Route::get('users/permission','UsersController@permission');
   Route::get('users/manage','UsersController@manage');
   Route::resource('users', 'UsersController');

   Route::get('home/joinus','HomeController@joinus');
   Route::resource('home', 'HomeController');
   Route::resource('clinic', 'ClinicController');
   Route::resource('dentists', 'DentistsController');

   Route::post('exams/get','PatientExamsController@getExams');
   Route::resource('exams', 'PatientExamsController');

   Route::post('pictogram/getPictogram','PictogramController@getPictogram');
   Route::resource('pictogram', 'PictogramController');

   Route::get('/patient/getCities/{id}','PatientsController@getCities');
   Route::get('/patient/getBoroughs/{id}','PatientsController@getBoroughs');
   Route::post('patients/getPatients','PatientsController@getPatientList');
   Route::get('patients/stats','PatientsController@stats');
   Route::resource('patients', 'PatientsController');

   Route::get('calendar/appointmentdetails/{id}','CalendarController@appointmentdetails');
   Route::put('calendar/updateStatus/{id}','CalendarController@updateStatus');
   Route::get('calendar/appointmentTypes','CalendarController@appointmentTypes');
   Route::post('calendar/addAppointmentType','CalendarController@addAppointmentTypes');
   Route::post('calendar/updateAppointment/{id}','CalendarController@updateAppointment');
   Route::post('calendar/addDocument','CalendarController@addDocument');
   Route::post('calendar/deleteDocument/{id}','CalendarController@deleteDocument');
   Route::post('calendar/getPatientTreatmentDocuments','CalendarController@getPatientTreatmentDocuments');
   Route::post('calendar/addQuotation','CalendarController@addQuotation');
   Route::post('calendar/getQuotation','CalendarController@getQuotation');
   Route::post('calendar/summary','CalendarController@summary');

   Route::post('calendar/getTodaysEvents','CalendarController@getTodaysEvent');
   Route::resource('calendar', 'CalendarController');

   Route::resource('holidays', 'HolidaysController');
   Route::resource('recepnists', 'RecepnistsController');
    Route::resource('consultation', 'ConsultationController');

   // Route::get('treatments/treatmentTypes','TreatmentController@treatmentTypes');
   // Route::post('treatments/addTreatmentType','TreatmentController@addTreatmentTypes');
   Route::post('treatments/getPatientTreatment','TreatmentController@getPatientTreatment');
   Route::resource('treatments', 'TreatmentController');

   Route::get('specialities/get','SpecialityController@get');
   Route::resource('specialities', 'SpecialityController');

   Route::resource('treatmenttypes', 'TreatmentTypesController');

   Route::get('dentalplans/permission','DentalplansController@permission');
   Route::resource('dentalplans', 'DentalplansController');

   Route::get('permissions/addPermissions','PermissionsController@addPermissions');
   //Route::get('permissions/assign','PermissionsController@assign');
   Route::get('permissions/assignPermissions','PermissionsController@assign');
   Route::post('permissions/saveRole','PermissionsController@saveRole');
   Route::resource('permissions', 'PermissionsController');

   Route::get('quoteitems','StockControlController@quoteItems');
   Route::get('getItemHistory/{id}','StockControlController@getItemHistory');
   Route::put('updateStock/{id}','StockControlController@updateStock');
   Route::resource('stockcontrol', 'StockControlController');
   Route::resource('contacts', 'ItemContactsController');

   Route::put('updateReminderUserStatus/{id}','ReminderController@updateReminderUserStatus');
   Route::put('updateStatus/{id}','ReminderController@updateStatus');
   Route::put('unmarkReminder/{id}','ReminderController@unmarkReminder');
   Route::resource('reminders', 'ReminderController');


   Route::resource('agenda', 'AgendaController');
   Route::resource('holidays', 'AppointmentHolidaysController');

   Route::resource('firsttime', 'FirstimeController');

});

Route::get('billing/subscribe', 'UserBilling@subscribeuser');
Route::resource('billing', 'UserBilling');

resources/views/billing/index.blade.php
@extends('layouts.page')
@section('content')
<div class="main-content">
   <div class="container">

      <div class="panel" style="@if(isset($myReminders[0])) display:none; @endif;opacity: 0.7;border-radius: 1px;background-color: White;margin-top: 15px">
         <span style="display: inline"><p style="padding: 25px;font-size: large;color: #737373"><i class="fa fa-warning fa-lg fa-fw" style="color: Gold!important;"></i>&nbsp;&nbsp;&nbsp;You may have payments pending. <a href="{{ url('/billing/subscribe') }}">Pay Here</a></p></span>
      </div>

   </div>
</div>
@endsection

resources/views/billing/subscribe.blade.php
@extends('layouts.stripe')
@section('content')
   <?php $user = Auth::user();?>
   @if($user->hasRole('dentistadmin'))
      <div class="main-content">
         <div class="container">
            <div class="panel panel-white" style="margin-top:15px;">
               <div class="panel-body">
                  <h2 style="font-weight: lighter">Subscription Payment Details</h2>

                   <hr style="margin-top: 15px;margin-bottom: 20px;border: 0;border-top: 1px solid lightskyblue">

                  {!! Form::open(['url' => route('billing.store'), 'data-parsley-validate', 'id' => 'payment-form']) !!}
                      @if ($message = Session::get('success'))

                      <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                              <strong>{{ $message }}</strong>
                      </div>
                      @endif
                      <div class="form-group" id="product-group">
                          {!! Form::label('plan', 'Select Plan') !!}
                          {!! Form::select('plan', ['Monthly' => 'Monthly ($9.99)', 'Yearly' => 'Yearly ($99.99)'], 'Book', [
                              'class'                         => 'form-control',
                              'required'                      => 'required',
                              'data-parsley-class-handler'    => '#product-group'
                              ]) !!}
                      </div>
                      <div class="form-group" id="cc-group">
                          {!! Form::label(null, 'Card Number') !!}
                          {!! Form::text(null, null, [
                              'class'                         => 'form-control',
                              'required'                      => 'required',
                              'data-stripe'                   => 'number',
                              'data-parsley-type'             => 'number',
                              'maxlength'                     => '16',
                              'placeholder'                   => '0000 0000 0000 0000',
                              'data-parsley-trigger'          => 'change focusout',
                              'data-parsley-class-handler'    => '#cc-group'
                              ]) !!}
                      </div>
                      <div class="form-group" id="ccv-group">
                          {!! Form::label(null, 'CVC (3 or 4 digits):') !!}
                          {!! Form::text(null, null, [
                              'class'                         => 'form-control',
                              'required'                      => 'required',
                              'data-stripe'                   => 'cvc',
                              'data-parsley-type'             => 'number',
                              'placeholder'                   => '000 or 0000',
                              'data-parsley-trigger'          => 'change focusout',
                              'maxlength'                     => '4',
                              'data-parsley-class-handler'    => '#ccv-group'
                              ])!!}
                      </div>
                      <div class="row" >
                        <div class="col-md-2">
                          <div class="form-group" id="exp-m-group">
                              {!! Form::label(null, 'Month Exp.') !!}
                              {!! Form::selectMonth(null, null, [
                                  'class'                 => 'form-control',
                                  'required'              => 'required',
                                  'data-stripe'           => 'exp-month'
                              ], '%m') !!}
                          </div>
                          <div class="form-group" id="exp-y-group">
                              {!! Form::label(null, 'Year Exp.') !!}
                              {!! Form::selectYear(null, date('Y'), date('Y') + 10, null, [
                                  'class'             => 'form-control',
                                  'required'          => 'required',
                                  'data-stripe'       => 'exp-year'
                                  ]) !!}
                          </div>
                        </div>
                      </div>
                        <div class="form-group">
                            {!! Form::submit('Make Payment', ['class' => 'btn btn-squared btn-lg btn-block btn-primary btn-order', 'id' => 'submitBtn', 'style' => 'margin-bottom: 10px;border-radius:1px']) !!}
                        </div>
                        <div class="row">
                          <div class="col-md-12">
                              <span class="payment-errors" style="color: red;margin-top:10px;"></span>
                          </div>
                        </div>
                    {!! Form::close() !!}

               </div>
            </div>

         </div>
      </div>
   @else
   <div class="main-content">
      <div class="container">
         <div class="panel panel-white" style="margin-top:15px;">
            <div class="panel-body">
               Please Contact Site admin to make payments.
            </div>
         </div>
      </div>
   </div>
   @endif;

@endsection